config/routes.rb
Gtcbe::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
	# Static pages
	#root 'static_pages#home'
	root 'blogposts#index'
	match '/register', to: 'users#new', via: 'get'
	match '/login', to: 'sessions#new', via: 'get'
	match '/logout', to: 'sessions#destroy', via: 'delete'
	match '/blog', to: 'blogposts#index' , via: 'get'
	match '/wiki', to: 'wiki_pages#home', via: 'get'

	
	#users
	resources :users, only: [ :new, :create, :show, :edit, :update]
	
	#sessions
	resources :sessions, only: [ :create, :destroy ]
	
	#blogposts
	resources :blogposts, only: [ :index, :show ]
	
	#password resets
	resources :password_resets, only: [ :new, :edit, :create, :update ]
	
	#comments
	resources :comments, only: [ :new, :create, :show, :edit, :update ] do
		member do
			patch 'upvote'
			patch 'downvote'
		end
	end
	
	#wiki pages
	resources :wiki_pages, only: [ :show ] do
		member do
			get 'home'
		end
	end
	
	#admin
	namespace :admin do
		get '', to: 'dashboard#index', as: '/'
		
		resources :users
		resources :blogposts
		resources :wiki_pages
		resources :wiki_hierarchies
		resources :comments
		
		get "wiki_pages/new/*page_name", to: "wiki_pages#new"
	end
	
	DynamicRouter.load
	
	get "wiki/*page_name", to: "wiki_pages#default"
	
 end

app/views/shared/_comments_form.html.erb
<div id="comment-form" class="row">
<span class="col-md-9">
<h4>Leave a comment:</h4>

<%= form_for(@comment) do |f| %>
	
		<%= f.hidden_field :commentable_id %>
		<%= f.hidden_field :commentable_type %>

		<div id="comment-title">
			<%= f.label :title %>
			<%= f.text_area :title, placeholder: "(optional)", cols: 95, size: 100, rows: 1 %>
		</div>
		
		<div id="comment-text">
			<%= f.label :text %>
			<%= f.text_area :text, placeholder: "Enter comment ...", cols:95, rows: 5 %>
		</div>
		
		<%= f.submit "Post", class: "btn pull-right", id:"btn-post" %>
<% end %>
</span>
</div>

app/views/shared/_login_form.html.erb
<%= form_for(:session, url: sessions_path) do |f| %>
	<div class="form-input-holder">
		<%= f.text_field :email, placeholder: "Email"  %>
	</div>
	<div class="form-input-holder">
		<%= f.password_field :password, placeholder: "Password" %>
	</div>
	<div id="login_buttons">
		<%= link_to "Sign up".upcase, new_user_path, id: "link-signup" %>
		<%= f.submit "Log in".upcase, class: "btn btn-xs", id: "btn-login" %>
	</div>
<% end %>

app/views/shared/_reply_form.html.erb
<li id="reply-form" class="row">
<span class="col-md-9 col-md-offset-3">
<%= form_for(:comment, url: comments_path) do |f| %>
	
		<%= f.hidden_field :commentable_id, id:"reply_commentable_id" %>
		<%= f.hidden_field :commentable_type, id:"reply_commentable_type" %>
		
		<div id="reply-text"  class="pull-right" >
			<%= f.text_area :text, placeholder: "Reply ...", cols:95, rows: 2 %>
			<%= f.submit "Reply", class: "btn btn-xs  pull-right", id:"btn-reply" %>
		</div>
<% end %>
</span>
</li>