config/routes.rb
Gtcbe::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
	# Static pages
	#root 'static_pages#home'
	root 'blogposts#index'
	match '/register', to: 'users#new', via: 'get'
	match '/login', to: 'sessions#new', via: 'get'
	match '/logout', to: 'sessions#destroy', via: 'delete'
	match '/blog', to: 'blogposts#index' , via: 'get'
	match '/wiki', to: 'wiki_pages#home', via: 'get'

	
	#users
	resources :users, only: [ :new, :create, :show, :edit, :update]
	
	#sessions
	resources :sessions, only: [ :create, :destroy ]
	
	#blogposts
	resources :blogposts, only: [ :index, :show ]
	
	#password resets
	resources :password_resets, only: [ :new, :edit, :create, :update ]
	
	#comments
	resources :comments, only: [ :new, :create, :show, :edit, :update ] do
		member do
			patch 'upvote'
			patch 'downvote'
		end
	end
	
	#wiki pages
	resources :wiki_pages, only: [ :show ] do
		member do
			get 'home'
		end
	end
	
	#admin
	namespace :admin do
		get '', to: 'dashboard#index', as: '/'
		
		resources :users
		resources :blogposts
		resources :wiki_pages
		resources :wiki_hierarchies
		resources :comments
		
		get "wiki_pages/new/*page_name", to: "wiki_pages#new"
	end
	
	DynamicRouter.load
	
	get "wiki/*page_name", to: "wiki_pages#default"
	
 end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base

	before_save do
		self.name = name.gsub(/\s+/, '_').underscore
	end
	
	after_save :reload_routes
	
	belongs_to :user, :foreign_key => :author_id
	has_many :comments, dependent: :destroy, as: :commentable
	
	def comment_count
		count = 0;
		comments.each do |comment|
			count += comment.comments.count
		end
		count += comments.count
	end

	default_scope -> { order('created_at DESC') }
	validates :name, presence: true, length: { maximum: 140 }, uniqueness: { case_sensitive: false }
	validates :title, presence: true, length: { maximum: 140 }, uniqueness: { case_sensitive: false }
	
	private
	
		def reload_routes
			DynamicRouter.reload
		end
	
end

app/controllers/admin/blogposts_controller.rb
class Admin::BlogpostsController < Admin::AdminController

	def index
		@posts = Blogpost.all
	end
  
	def new
		@post = Blogpost.new
	end
	
	def create
		@post = current_user.blogposts.create(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end
	
	def edit
		@post = Blogpost.find(params[:id])
	end
	
	def update
		@post = Blogpost.find(params[:id])
		if @post.update_attributes(post_params)
			redirect_to admin_blogposts_url
		else
			render 'edit'
		end
	end
	
	def destroy
		Blogpost.find(params[:id]).destroy
		redirect_to admin_blogposts_url
	end
	
	
	private
  
		def post_params
			params.require(:blogpost).permit(:name, :title, :text)
		end
		
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController

	def index
		@posts = Blogpost.all
	end

	def show
		@post = Blogpost.find(params[:id])
		@comments = @post.comments.to_a # cast to array necessary so we don't have the dummy comment in the list
		
		if signed_in?
			@comment = @post.comments.build
		end
	end

end
 

app/helpers/admin/blogposts_helper.rb
module Admin::BlogpostsHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/views/admin/blogposts/edit.html.erb
<div class="row">
	<div class="col-md-8 offset-2">
			<%= form_for([:admin, @post]) do |f| %>
			
				<%= f.label :name %>
				<%= f.text_field :name, :value => @post.name %>
				
				<%= f.label :title %>
				<%= f.text_field :title, :value => @post.title %>
				
				<%= f.label :text %>
				<%= f.cktext_area :text, rows: 10, :value => @post.text %>
			
				<%= f.submit "Save", class: "btn btn-large btn-primary" %>
			<% end %>
	</div>
</div>

app/views/admin/blogposts/index.html.erb
<h1>Blogposts</h1>

<ul>
<% @posts.each do |post| %>
<li>
<%= post.id %>
<%= post.title %>
<%= User.find(post.author_id).name %>
<%= link_to "edit", edit_admin_blogpost_path(post), method: "get" %>
<%= link_to "delete", admin_blogpost_path(post), method: "delete" %>
</li>
<% end %>
</ul>

<%= link_to "New", new_admin_blogpost_path %>

app/views/admin/blogposts/new.html.erb
<div class="row">
	<div class="col-md-8 offset-2">
			<%= form_for([:admin, @post]) do |f| %>
			
				<%= f.label :name %>
				<%= f.text_field :name %>
				
				<%= f.label :title %>
				<%= f.text_field :title %>
				
				<%= f.label :text %>
				<%= f.cktext_area :text, rows: 10 %>
			
				<%= f.submit "Save", class: "btn btn-large btn-primary" %>
			<% end %>
	</div>
</div>