config/routes.rb
Gtcbe::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
	# Static pages
	#root 'static_pages#home'
	root 'blogposts#index'
	match '/register', to: 'users#new', via: 'get'
	match '/login', to: 'sessions#new', via: 'get'
	match '/logout', to: 'sessions#destroy', via: 'delete'
	match '/blog', to: 'blogposts#index' , via: 'get'
	match '/wiki', to: 'wiki_pages#home', via: 'get'

	
	#users
	resources :users, only: [ :new, :create, :show, :edit, :update]
	
	#sessions
	resources :sessions, only: [ :create, :destroy ]
	
	#blogposts
	resources :blogposts, only: [ :index, :show ]
	
	#password resets
	resources :password_resets, only: [ :new, :edit, :create, :update ]
	
	#comments
	resources :comments, only: [ :new, :create, :show, :edit, :update ] do
		member do
			patch 'upvote'
			patch 'downvote'
		end
	end
	
	#wiki pages
	resources :wiki_pages, only: [ :show ] do
		member do
			get 'home'
		end
	end
	
	#admin
	namespace :admin do
		get '', to: 'dashboard#index', as: '/'
		
		resources :users
		resources :blogposts
		resources :wiki_pages
		resources :wiki_hierarchies
		resources :comments
		
		get "wiki_pages/new/*page_name", to: "wiki_pages#new"
	end
	
	DynamicRouter.load
	
	get "wiki/*page_name", to: "wiki_pages#default"
	
 end

app/models/wiki_page.rb
class WikiPage < ActiveRecord::Base

	before_save do
		self.name = name.gsub(/\s+/, '_').underscore
	end
	
	has_many :comments, dependent: :destroy, as: :commentable
	has_many :child_relations, class_name: "WikiHierarchy", dependent: :nullify , foreign_key: "parent_id"
	has_one :parent_relation, class_name: "WikiHierarchy", dependent: :destroy, foreign_key: "child_id"

	def comment_count
		count = 0;
		comments.each do |comment|
			count += comment.comments.count
		end
		count += comments.count
	end
	
	#default_scope -> { order('created_at DESC') }
	validates :name, presence: true, length: { maximum: 140 }, uniqueness: { case_sensitive: false }
	validates :title, presence: true, length: { maximum: 140 }, uniqueness: { case_sensitive: false }
	
end

app/controllers/admin/wiki_pages_controller.rb
class Admin::WikiPagesController < Admin::AdminController

	def index
		@pages = WikiPage.all
	end
  
	def new
		if 	page_name = params[:page_name]
			@page = WikiPage.new(name: page_name, title: page_name.humanize)
		else
			@page = WikiPage.new
		end
	end
	
	def create
		@page = WikiPage.create(page_params)
		if @page.save
			DynamicRouter.reload
			WikiHierarchy.create( parent_id: 0, child_id: @page.id)
			redirect_to @page
		else
			render 'new'
		end
	end
	
	def edit
		@page = WikiPage.find(params[:id])
	end
	
	def update
		@page = WikiPage.find(params[:id])
		if @page.update_attributes(page_params)
			DynamicRouter.reload
			redirect_to @page
		else
			render 'edit'
		end
	end
	
	def destroy
		page = WikiPage.find(params[:id])
		if page
			page.destroy
			DynamicRouter.reload
			redirect_to admin_wiki_pages_url
		end
	end
	
	
	private
  
		def page_params
			params.require(:wiki_page).permit(:name, :title, :text)
		end

end

app/controllers/wiki_pages_controller.rb
class WikiPagesController < ApplicationController

def home
	@hierarchies = WikiHierarchy.all
	@wiki_page = WikiPage.first
	loadComentsFor(@wiki_page)
	render :action => "show"
end

def default
	page_name = params[:page_name]
	text = "This page does not exist yet"
	@wiki_page = WikiPage.new(name: page_name, title: page_name.humanize, text: text)
end

def show
	@hierarchies = WikiHierarchy.all
	@wiki_page = WikiPage.find(params[:id])
	loadComentsFor(@wiki_page)
end

	private

		def loadComentsFor(page)
			@comments = page.comments.to_a
			
			if signed_in?
				@comment = page.comments.build
			end
		end

end

app/helpers/admin/wiki_pages_helper.rb
module Admin::WikiPagesHelper

end

app/helpers/wiki_pages_helper.rb
module WikiPagesHelper

	def process_text text
		regex = /(@(\w+))/
	
		text.gsub(regex) do |match|
			page_name = $2
			page = WikiPage.find_by(name: page_name)
			if(page)
				link_to page.title, "#{wiki_path}/#{page_name}", :class => "valid_link"
			else
				link_to page_name.humanize, "#{wiki_path}/#{page_name}", :class => "invalid_link"
			end
		end
	end

	def cache_key_for_wiki_pages
		count          = WikiPage.count
		max_updated_at = WikiPage.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"wiki_pages/all-#{count}-#{max_updated_at}"
	end
	
end

app/views/wiki_pages/_recursive_hierarchy.html.erb
<li>
	<% children = p_hierarchies.select { |item| item.parent_id == p_hierarchy.child_id } %>
	<% if children.any?  %>
	<button type="button" data-toggle="collapse" data-target="<%= "#list_#{p_hierarchy.child.name}" %>">
		+
	</button>
	<% end %>
	<%= link_to p_hierarchy.child.title, wiki_url+"/#{p_hierarchy.child.name}" %>

</li>
<% if children.any?  %>
	<ul class="collapse in" id="<%= "list_#{p_hierarchy.child.name}" %>">
		<% children.each do |hierarchy| %>
			<%= render partial:"recursive_hierarchy", locals: { p_hierarchy: hierarchy, p_hierarchies: p_hierarchies }%>
		<% end %>
	</ul>
<% end  %>

app/views/wiki_pages/_sidebar.html.erb
<ul>
	<% cache(cache_key_for_wiki_pages) do %>
		<% @hierarchies.select { |item| item.parent_id.nil? || item.parent_id == 0 }.each do |hierarchy| %>
			<%= render partial:"recursive_hierarchy", locals: { p_hierarchy: hierarchy, p_hierarchies: @hierarchies }%>
		<% end %>
	<% end %>
</ul>

app/views/wiki_pages/_wiki_page.html.erb
<div class="row blog-header">
	<h1 class="col-md-*"><%= link_to wiki_page.title, wiki_url+"/#{wiki_page.name}" %></h1>
	<% if wiki_page.created_at %>
		<small class><%= wiki_page.updated_at == wiki_page.created_at ? "Created" : "Last updated" %> <%= time_ago_in_words(wiki_page.updated_at) %> ago</h3>
	<% end %>
</div>
<p><%= process_text(wiki_page.text).html_safe %></p>
<% if current_user && current_user.is_administrator? %>
	<div class="actions">
	<% if wiki_page.id %>
		<%= link_to "Edit", edit_admin_wiki_page_url(@wiki_page) %>
	<% else %>
		<%= link_to "Edit", "#{new_admin_wiki_page_url}/#{@wiki_page.name}" %>
	<% end %>
	</div>
<% end %>

app/views/wiki_pages/default.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<section>
		<%= render @wiki_page %>
		</section>
	</div>
</div>

app/views/wiki_pages/show.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render partial:"sidebar" %>
	</div>
	<div class="col-md-8">
		<section>
		<%= render @wiki_page %>
		</section>
		<hr>
		<section id="comments">
			<h3>Comments (<%= @wiki_page.comment_count %>)</h3>
			<% if signed_in?  %>
				<%= render "shared/comments_form" %>
				<%= render "shared/reply_form" %>
			<% else %>
				<div class="alert alert-danger">
					Please <%= link_to "log in", :login %> or <%= link_to "sign up", register_url %> to comment.
				</div>
			<% end %>
			<% if @wiki_page.comments.any? %>
				<ol class="comments">
					<%= render @comments %>
				</ol>
			<% end %>
		</section>
		<section>
		</section>
	</div>
</div>